### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/primgrp#1]
- [x] The current `README.md` has only the title
- [x] The manual is missing at the moment
- [x] Meta-information in `PackageInfo.g` needs updating
- [x] List of authors has to be checked
- [x] Create package website

**Comment by alex-konovalov** [comment]
@colva @hulpke @ChristopherRussell three of you are authors of this package - does it include any other code, perhaps by @bh11? Please advice me who should be in the list of authors.

**Comment by colva** [comment]
No idea I’m afraid. Who is bh11?

Colva

> On 23 Oct 2017, at 10:18, Alexander Konovalov <notifications@github.com> wrote:
> 
> @colva @hulpke @ChristopherRussell three of you are authors of this package - does it include any other code, perhaps by @bh11? Please advice me who should be in the list of authors.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gap-packages/primgrp","title":"gap-packages/primgrp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gap-packages/primgrp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alex-konovalov in #1: @colva @hulpke @ChristopherRussell three of you are authors of this package - does it include any other code, perhaps by @bh11? Please advice me who should be in the list of authors."}],"action":{"name":"View Issue","url":"https://github.com/gap-packages/primgrp/issues/1#issuecomment-338598533"}}}!

*************************************

Colva Roney-Dougal
Reader in Pure Mathematics
Director of the Centre for Interdisciplinary Research in Computational Algebra
Editor of Proceedings A of the Royal Society of Edinburgh
Editor of Royal Society Open Science
Director of Undergraduate Mathematics Admissions

The University of St Andrews is a charity registered in Scotland : No SC013532

**Comment by alex-konovalov** [comment]
@colva: Burkhard Höfling - https://github.com/bh11

**Comment by alex-konovalov** [comment]
Haven't heard from any of the authors - so, shall I assume that the current list of authors is correct?

**Comment by colva** [comment]
Hi Alexander

The one thing I can see that’s definitely wrong is that my old email address is there. I”m afraid I don’t know how to edit it, but it should probably be my @st-andrews one

Colva


> On 26 Oct 2018, at 23:01, Alexander Konovalov <notifications@github.com> wrote:
> 
> Haven't heard from any of the authors - so, shall I assume that the current list of authors is correct?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gap-packages/primgrp","title":"gap-packages/primgrp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gap-packages/primgrp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alex-konovalov in #1: Haven't heard from any of the authors - so, shall I assume that the current list of authors is correct?"}],"action":{"name":"View Issue","url":"https://github.com/gap-packages/primgrp/issues/1#issuecomment-433555135"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/gap-packages/primgrp/issues/1#issuecomment-433555135", "url": "https://github.com/gap-packages/primgrp/issues/1#issuecomment-433555135", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [gap-packages/primgrp] Complete documentation (#1)", "sections": [ { "text": "", "activityTitle": "**Alexander Konovalov**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@alex-konovalov", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"gap-packages/primgrp\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"gap-packages/primgrp\",\n\"issueId\": 1\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/gap-packages/primgrp/issues/1#issuecomment-433555135" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 153183117\n}" } ], "themeColor": "26292E" } ]

*************************************

Colva Roney-Dougal
Professor of Pure Mathematics
Director of the Centre for Interdisciplinary Research in Computational Algebra
Editor of London Mathematical Society Lecture Notes Series
Editor of Proceedings A of the Royal Society of Edinburgh
Director of Undergraduate Mathematics Admissions

The University of St Andrews is a charity registered in Scotland : No SC013532

**Comment by alex-konovalov** [comment]
@colva Thanks, updated it in be8ca24ff42c410b94fafdd2fddde29aa10ef624. It will appear in the next release.
