### ISSUE TITLE
PrimitiveGroup(125,17);

### ISSUE THREAD

**Issue by hulpke** [gap-packages/primgrp#25]
has name

5^3:(2 x 91:3)

the 91 need to be 31. I can add a fix to #24 if someone resolves the code coverage blockage for merging.

**Comment by fingolfin** [comment]
I am not sure what "code coverage blockage" refers to?

**Comment by hulpke** [comment]
@fingolfin My previous PR #24 cannot be merged, because codecov reports a low coverage for the (5) lines of the diff, and it is configured to require essentially 100% coverage to allow merge.
Changing the name of the other group will run into the same problem.

**Comment by fingolfin** [comment]
It can be merged just fine. I get the "merge" button, and I just double checked: no branch protection rules are active on thus repository. So you could merge it even if the Travis tests failed (nit that I'd recommend it).

**Comment by hulpke** [comment]
Thank you -- I misingterpreted ``checks not succesful''. Can I add this name fix to the same PR, or should I open another one?

**Comment by fingolfin** [comment]
You can really fo here as you please :-). Personally I think it is fine to add it to the existing PR
