### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/primgrp#27]
This package has accumulated several bug fixes since its last release (3.3.2 in October 2018). It would be good to release those to the public, ideally in time for GAP 4.11.

I'd take care of it, but I am not a package maintainer (@hulpke @alex-konovalov @ChristopherRussell are). If you are willing to add "The GAP team" as a maintainer, I can take care of the release. Otherwise, somebody else should. It's not much work, really: update the version and release date in `PackageInfo.g` and `CHANGES.md`, and then run the `release` script from ReleaseTools.

**Comment by alex-konovalov** [comment]
Which version should it be - 3.3.3 or 3.4.0?

**Comment by fingolfin** [comment]
Perhaps 3.4 because the performance of `PrimitiveIdentification` was improved? But really, anything is fine from my POV :-).

**Comment by alex-konovalov** [comment]
I thought of 3.4.0 too. I will make a release.

**Comment by alex-konovalov** [comment]
Done at https://github.com/gap-packages/primgrp/releases/tag/v3.4.0
