### ISSUE TITLE
Require GAP 4.10.0 or higher

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/primgrp#39]
GAP 4.9 tests have harmless diffs, but those obstruct testing, because Travis CI test fails. 

With GAP 4.10.0 released in November 2018, it should be fine to require GAP 4.10 or newer. 

Any objections @hulpke @colva @fingolfin ?

**Comment by alex-konovalov** [comment]
Would be nice to make a new release before GAP 4.11.1 or 4.12. So I think it's will be fine to require 2-year old GAP version by then (ping to @hulpke @colva @fingolfin).

**Comment by hulpke** [comment]
No objections -- 4.9 users still have the old version

**Comment by colva** [comment]
Fine by me

Colva


> On 2 Oct 2020, at 22:56, Alexander Hulpke <notifications@github.com> wrote:
> 
> 
> No objections -- 4.9 users still have the old version
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/gap-packages/primgrp/issues/39#issuecomment-702974875", "url": "https://github.com/gap-packages/primgrp/issues/39#issuecomment-702974875", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

*************************************

Colva Roney-Dougal
Professor of Pure Mathematics
Director of Undergraduate Mathematics Admissions

The University of St Andrews is a charity registered in Scotland : No SC013532
