### ISSUE TITLE
Transition plan for the PrimGrp package

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/primgrp#5]
History of changes in the core GAP system (tick means no need to revisit):
- [ ] https://github.com/gap-system/gap/issues/791
- [ ] https://github.com/gap-system/gap/pull/818
- [ ] https://github.com/gap-system/gap/issues/832
- [ ] https://github.com/gap-system/gap/issues/833
- [ ] https://github.com/gap-system/gap/issues/834
- [ ] https://github.com/gap-system/gap/pull/851 
- [ ] https://github.com/gap-system/gap/issues/852
- [ ] https://github.com/gap-system/gap/issues/1012

Remark by @alex-konovalov: please don't close this until I will check all boxes myself.

**Comment by alex-konovalov** [comment]
The plan, outlined in https://github.com/gap-system/gap/issues/791 is to do one step at a time. In more details:

- [ ] Release the PrimGrp package
- [ ] Pick it up for the redistribution with GAP
- [ ] Further tests with Jenkins
- [ ] Add PrimGrp to www.gap-system.org/pub/gap/gap4pkgs/packages-master.tar.gz archive
- [ ] Temporary replace bootstrap-pkg-full.tar.gz by packages-master.tar.gz for the master branch
- [ ] Make PrimGrp needed to run GAP
- [ ] Remove `prim` directory and relevant parts of the documentation

Packages that use `prim` (CTblLib and IRREDSOL) should not see any differences because PrimGrp is needed. They are recommended to specify PrimGrp in their dependencies in their next release. After the new releases of these packages are picked up for the redistribution, the transitive group package may be removed from needed to run GAP, and moved to loaded by default.

**Comment by alex-konovalov** [comment]
Some examples of diffs in Jenkins nightly tests. Errors like that should disappear when the package will become required to run GAP. Some of the tests may eventually migrate to the PrimGrp package.


```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/install/label/kovacs/GAP-master-snapshot/tst/testinstall/opers/Mini\
malNormalSubgroups.tst:41
# Input is:
MinimalNormalSubgroups(PrimitiveGroup(8,3)) = [ Group([ (1,7)(2,8)(3,5)(4,6), \
(1,3)(2,4)(5,7)(6,8), (1,2)(3,4)(5,6)(7,8) ]) ];
# Expected output:
true
# But found:
Error, the Primitive Groups library is required but not installed
########
```
```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/install/label/kovacs/GAP-master-snapshot/tst/testinstall/opers/Norm\
alHallSubgroups.tst:43
# Input is:
List(AllPrimitiveGroups(DegreeAction, 8), G -> List(NormalHallSubgroups(G), Si\
ze));
# Expected output:
[ [ 1, 56, 8 ], [ 1, 168, 56, 8 ], [ 1, 1344 ], [ 1, 168 ], [ 1, 336 ], 
  [ 1, 20160 ], [ 1, 40320 ] ]
# But found:
Error, Variable: 'AllPrimitiveGroups' must have a value
########
```
```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/testextra/grpconst.ts\
t:13
# Input is:
if LoadPackage( "grpconst", false )=fail then
Print("\n\n",
"*** Since you do not have the `grpconst' package installed,    ***\n",
"*** you will get some error messages. They should be ignored.  ***\n\n\n");
fi;
# Expected output:
# But found:
Error, Variable: 'DegreeOfMatrixGroup' must have a value
Error, was not in any namespace
Error, was not in any namespace
########
```

**Comment by fingolfin** [comment]
What is the status of this issue, @alex-konovalov? Do those jenkin tests still fail?

**Comment by alex-konovalov** [comment]
@fingolfin jenkins tests pass since the package is now required to run GAP. Still, as I said below, let me check all tickboxes before I close this.

**Comment by alex-konovalov** [comment]
I am still going to look at the checklist...

**Comment by fingolfin** [comment]
It has been three years since the last comment here. I am not aware of anything "to be done", at least not for "the migration" which arguably was completed five years ago...

Thus, I am closing this now.
